homepage:
   path:   /
   controller: App\Controller\GeneralController::index
homepage2:
   path:   /home
   controller: App\Controller\GeneralController::index
index:
   path: /{slug}
   controller: App\Controller\GeneralController::show