<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKfA6d72\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKfA6d72/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKfA6d72.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKfA6d72\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKfA6d72\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KfA6d72',
    'container.build_id' => '2380a607',
    'container.build_time' => 1564694182,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKfA6d72');
